name: CI
on:
  push:
    branches:
      - "**"
jobs:
  test:
    name: rust_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --workspace
  build_site:
    name: build_site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.4.0
      - name: Install and Build
        run: |
          cd guide-site
          npm ci
          npm run wasm
          npm run build
